### ISSUE TITLE
PDF Generator Call

### ISSUE THREAD

**Issue by eiskasten** [mknentwich/core#12]
**Is your feature request related to a problem? Please describe.**
I simply want to generate a PDF with an order id only.

**Describe the solution you'd like**
A function in the pdf package has to be exposed which takes only an order id and returns either an `os.File`or an `io.Writer`. `io.Writer` should be preferred as generated PDFs are read only and writers can simply wrapped into a file.

**Describe alternatives you've considered**
There does not exist an alternative, this feature is required in that manner.

**Comment by deoknats861** [comment]
Fixed with dc3344cb231a915edefa66be0a984cf40c62f988
